# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
url: http://sda.tech/ # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ""
title: Smart Data Analytics
temp: temp value
titleWithAcronym: Smart Data Analytics (SDA)
author: Institut für Informatik III
email: jens.lehmann@cs.uni-bonn.de
copyrights: Smart Data Analytics, © 2019
addressLineOne: Endenicher Allee 19a
addressLineTwo: 53115 Bonn, Germany
phone: +49 228 73-4315
fax: +49 228 73-4382
description: The Smart Data Analytics (SDA) research group, led by Prof. Dr. Jens Lehmann, has members from the Institute for Computer Science at the University of Bonn, the Fraunhofer Institute for Intelligent Analysis and Information Systems (IAIS) and the Institute for Applied Computer Science Leipzig. At its core, the group investigates machine learning techniques ("analytics") using structured knowledge ("smart data"). The group aims at covering the full spectrum of research including theoretical foundations, algorithms, prototypes and industrial applications.
logo: http://sda.cs.uni-bonn.de/wp-content/uploads/2016/02/candidate1m.png

eisName: Institute for Computer Science
eisHomePage: https://www.iai.uni-bonn.de/en

uniBonnName: University of Bonn
uniBonnHomePage: https://www.uni-bonn.de/

fraunhoferDepartmentName: Fraunhofer Institute for Intelligent Analysis and Information Systems (IAIS)
fraunhoferHomePage: https://www.iais.fraunhofer.de/

leipzigDepName: Institute for Applied Computer Science Leipzig
LeipzigHomePage: http://infai.org/de/Aktuelles

 # the subpath of your site, e.g. /blog
# twitter_username: SDA_Research
github_username: mediaprophet
facebook_username: SDAResearch
linkedin_username: ubiquitous

# BibBase URL
bibbase: http://bibbase.org/show?bib=https://raw.githubusercontent.com/SmartDataAnalytics/sda.tech/master/sda.bib

#activeVars
activePeople: All Members
activeGroup: Distributed Semantic Analytics
currentSemester: Summer
currentYear: 2019
leader: Prof.Dr. Jens Lehmann
leaderHomePage: http://jens-lehmann.org/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-rdf
  - jekyll-twitter-plugin
  - jekyll-email-protect

#Configuration of jekyll-rdf in our template
jekyll_rdf:
    path: "rdf-data/sda.tech.ttl"
    language: "en"
    include_blank: true
    render_orphaned_uris: true
    restriction: "SELECT ?resourceUri WHERE {
                 { ?resourceUri a <http://example.org/group> . }
                UNION { ?resourceUri a <http://example.org/project> . }
                UNION { ?resourceUri a <http://example.org/publication> . }
                UNION { ?resourceUri a <http://sda.tech/Group> . }
                UNION { ?resourceUri a <http://sda.tech/Blog> . }
                UNION { ?resourceUri a <http://rdfs.org/sioc/ns#Post> . }
                UNION { ?resourceUri a <http://sda.tech/Partner> . }
                UNION { ?resourceUri a <http://sda.tech/Course> . }
                UNION { ?resourceUri a <http://sda.tech/Job> . }
                UNION { ?resourceUri a <http://xmlns.com/foaf/0.1/Project> . }
                UNION { ?resourceUri a <http://xmlns.com/foaf/0.1/Person> . }
                UNION { ?resourceUri a <http://xmlns.com/foaf/0.1/Document> . }
                }"
    default_template: "default.html"
    class_template_mappings:
        "http://xmlns.com/foaf/0.1/Person" : "person.html"
        "http://sda.tech/Group" : "group.html"
        "http://rdfs.org/sioc/ns#Post" : "post.html"
        "http://xmlns.com/foaf/0.1/Project" : "project.html"
        "http://sda.tech/Partner" : "partners.html"
        "http://sda.tech/Job" : "job.html"
        "http://sda.tech/Course" : "teaching.html"
        "http://xmlns.com/foaf/0.1/Document" : "page.html"
    instance_template_mappings:
        "http://sda.tech/" : "home.html"
        "http://sda.tech/group" : "groupmain.html"
        "http://sda.tech/partners" : "partners.html"
        "http://sda.tech/about" : "page.html"
        #People
        "http://sda.tech/people" : "people.html"
        "http://sda.tech/People/professors" : "personProfessors.html"
        "http://sda.tech/People/seniorresearchers" : "personSeniorResearchers.html"
        "http://sda.tech/People/phdstudents" : "personPhdStudents.html"
        "http://sda.tech/People/associatedresearchers" : "personAssociatedResearchers.html"
        "http://sda.tech/People/studentassistants" : "personStudentAssistants.html"
        "http://sda.tech/People/interns" : "personInterns.html"
        "http://sda.tech/People/formermembers" : "personFormerMembers.html"
        #CONTACT
        "http://sda.tech/contact" : "contact.html"
        #Thesis
        "http://sda.tech/thesis" : "thesis.html"
        "http://sda.tech/Thesis/bachelorthesis" : "bachelorthesis.html"
        "http://sda.tech/Thesis/masterthesis" : "masterthesis.html"
        "http://sda.tech/Thesis/ongoingthesis" : "ongoingthesis.html"
        "http://sda.tech/Thesis/frequentlyaskedquestions" : "faqthesis.html"
        #Projects
        "http://sda.tech/project" : "projectmain.html"
        "http://sda.tech/Project/fundedprojects" : "projectFunded.html"
        "http://sda.tech/Project/opensourceprojects" : "projectOpenSource.html"
        "http://sda.tech/Project/archivedprojects" : "projectArchived.html"
        "http://sda.tech/Project/incubatorprojects" : "projectIncubator.html"
        #Jobs
        "http://sda.tech/job" : "jobmain.html"
        "http://sda.tech/Job/akadimischerrat" : "akadJob.html"
        "http://sda.tech/Job/postdoctoral" : "postdocJob.html"
        "http://sda.tech/Job/phdposition" : "researchAssocJob.html"
        "http://sda.tech/Job/studentassistant" : "studentAssistantJob.html"
        "http://sda.tech/Job/environment" : "EnvoirnmentJob.html"
        "http://sda.tech/Job/frequentlyaskedquestions" : "FAQJob.html"
        #teaching
        "http://sda.tech/teaching" : "teachingmain.html"
        "http://sda.tech/Course/generalguidelines" : "teachingCourseGuidelines.html"
        "http://sda.tech/Course/oldcourses" : "teachingOldCourse.html"
        "http://sda.tech/Course/wintersemeter" : "teachingWinterSemester.html"
        "http://sda.tech/Course/summersummester" : "teachingSummerSemester.html"
        #partners
        "http://sda.tech/Partner/academicpartners" : "partnersAcademic.html"
        "http://sda.tech/Partner/industrypartners" : "partnersIndustry.html"
        #blog
        "http://sda.tech/blog" : "blog.html"
        "http://sda.tech/blog/papernotifications" : "blogPaperNotifications.html"
        "http://sda.tech/blog/invitedtalks" : "blogInvitedTalks.html"
        "http://sda.tech/blog/projectannouncements" : "blogProjectAnnouncements.html"
        "http://sda.tech/blog/generalposts" : "blogGeneralPosts.html"
        #publications
        "http://sda.tech/publication" : "publicationmain.html"
        "http://sda.tech/Publications/Conference" : "publicationconference.html"
        "http://sda.tech/Publications/Journal" : "publicationjournal.html"
        "http://sda.tech/Publications/ConferenceProceedings" : "publicationproceedings.html"
        "http://sda.tech/Publications/Book" : "publicationsbook.html"
        "http://sda.tech/Publications/TechnicalReport" : "publicationsreport.html"
        "http://sda.tech/Publications/Thesis" : "publicationsthesis.html"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
